name: "Has Changed"
description: "Test if commits have touched a matching file"
inputs:
  pattern: # id of input
    description: "File pattern to match"
    required: true
outputs:
  changed: # id of output
    description: "true if a change was made to a matching file; else false"
runs:
  using: "node12"
  main: "index.js"
