name: Test has-changed

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up environment
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: Code changed?
        id: changed
        uses: 99spokes/has-changed-action@master
        with:
          pattern: "**/*.js"
      - name: Log if match
        if: steps.changed.outputs.changed == "true"
        run: |
          echo "Changed!"
      - name: Log if no match
        if: steps.changed.outputs.changed == "false"
        run: |
          echo "Not changed!"
      - name: Always log
        run: |
          echo "Done!"
